<?xml version="1.0" encoding="utf-8"?><Database Name="ArgesPerm" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC-W10-SW\MSSQLSERVER_DEV;Initial Catalog=ArgesPerm;Integrated Security=True" SettingsObjectName="ArgPerm.Properties.Settings" SettingsPropertyName="ArgesPermConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="argarm.dirs" Member="dirs">
    <Type Name="dir">
      <Column Name="Hash" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Directory" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IdentityReference" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AccessControlType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileSystemRights" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="IsInherited" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="argarm.adusers" Member="adusers">
    <Type Name="aduser">
      <Column Name="SID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SamAccountName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistinguishedName" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="argarm.aduser_has_grp" Member="aduser_has_grps">
    <Type Name="aduser_has_grp">
      <Column Name="userSID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="groupSID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="argarm.adgroups" Member="adgroups">
    <Type Name="adgroup">
      <Column Name="SID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SamAccountName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistinguishedName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>