<?xml version="1.0" encoding="utf-8"?><Database Name="ArgesPerm" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC-W10-SW\MSSQLSERVER_DEV;Initial Catalog=ArgesPerm;Integrated Security=True" SettingsObjectName="ArgPerm.Properties.Settings" SettingsPropertyName="ArgesPermConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.adgroups" Member="adgroups">
    <Type Name="adgroup">
      <Column Name="SID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SamAccountName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DistinguishedName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsSecurityGroup" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="GroupScope" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.adusers" Member="adusers">
    <Type Name="aduser">
      <Column Name="SID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SamAccountName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DistinguishedName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UserPrincipalName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.grp_user" Member="grp_users">
    <Type Name="grp_user">
      <Column Name="userSID" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="grpSID" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.rights" Member="rights">
    <Type Name="right">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DirID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="IdentityReference" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AccessControlType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FileSystemRights" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="IsInherited" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="InheritanceFlags" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.dirs" Member="dirs">
    <Type Name="dir">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Directory" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>